steps:
  - id: "build and submit the dataflow job"
    name: maven:3.6.0-jdk-11-slim
    dir: 'dataflow'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./submit.sh DataflowDemoPipeline \
          --project=responsive-hall-125714 \
          --stagingLocation=gs://my-project-data-bucket/ \
          --gcpTempLocation=gs://my-project-data-bucket/ \
          --runner=DataflowRunner \
          --autoscalingAlgorithm=THROUGHPUT_BASED \
          --maxNumWorkers=10 \
          --jobName=demo \
          --region=us-central1
    waitFor: ['get build number']